import { v4 as uuidv4 } from 'uuid';
import type { Book } from './types';

export function generateSeedData(): Book[] {
  return [
    {
      id: uuidv4(),
      title: '1984',
      authors: ['George Orwell'],
      topics: ['Totalitarianism', 'Surveillance'],
      themes: ['Freedom', 'Truth', 'Power'],
      tags: ['classic', 'dystopia', 'must-read'],
      year: 1949,
      rating: 5,
      dateRead: '2023-06-15',
      notes: 'A chilling vision of a totalitarian future.',
    },
    {
      id: uuidv4(),
      title: 'Animal Farm',
      authors: ['George Orwell'],
      topics: ['Totalitarianism', 'Revolution'],
      themes: ['Power', 'Corruption', 'Equality'],
      tags: ['classic', 'allegory', 'short'],
      year: 1945,
      rating: 5,
      dateRead: '2023-05-20',
    },
    {
      id: uuidv4(),
      title: 'Brave New World',
      authors: ['Aldous Huxley'],
      topics: ['Technology', 'Social Control'],
      themes: ['Freedom', 'Happiness', 'Identity'],
      tags: ['classic', 'dystopia', 'sci-fi'],
      year: 1932,
      rating: 4,
      dateRead: '2023-07-10',
    },
    {
      id: uuidv4(),
      title: 'Fahrenheit 451',
      authors: ['Ray Bradbury'],
      topics: ['Censorship', 'Technology'],
      themes: ['Knowledge', 'Freedom', 'Conformity'],
      tags: ['classic', 'dystopia', 'sci-fi'],
      year: 1953,
      rating: 4,
      dateRead: '2023-08-05',
    },
    {
      id: uuidv4(),
      title: 'The Handmaid\'s Tale',
      authors: ['Margaret Atwood'],
      topics: ['Totalitarianism', 'Gender'],
      themes: ['Freedom', 'Power', 'Identity'],
      tags: ['dystopia', 'feminist', 'award-winner'],
      year: 1985,
      rating: 5,
      dateRead: '2023-09-12',
    },
    {
      id: uuidv4(),
      title: 'Dune',
      authors: ['Frank Herbert'],
      topics: ['Ecology', 'Politics', 'Religion'],
      themes: ['Power', 'Destiny', 'Survival'],
      tags: ['sci-fi', 'epic', 'must-read'],
      year: 1965,
      rating: 5,
      dateRead: '2023-10-01',
      notes: 'An epic tale of politics, religion, and ecology.',
    },
    {
      id: uuidv4(),
      title: 'Foundation',
      authors: ['Isaac Asimov'],
      topics: ['Technology', 'Politics', 'History'],
      themes: ['Knowledge', 'Civilization', 'Destiny'],
      tags: ['sci-fi', 'classic', 'series'],
      year: 1951,
      rating: 4,
      dateRead: '2023-11-15',
    },
    {
      id: uuidv4(),
      title: 'Neuromancer',
      authors: ['William Gibson'],
      topics: ['Technology', 'AI', 'Cyberpunk'],
      themes: ['Identity', 'Reality', 'Freedom'],
      tags: ['sci-fi', 'cyberpunk', 'influential'],
      year: 1984,
      rating: 4,
      dateRead: '2024-01-20',
    },
    {
      id: uuidv4(),
      title: 'Snow Crash',
      authors: ['Neal Stephenson'],
      topics: ['Technology', 'Language', 'Cyberpunk'],
      themes: ['Identity', 'Reality', 'Power'],
      tags: ['sci-fi', 'cyberpunk', 'action'],
      year: 1992,
      rating: 4,
      dateRead: '2024-02-10',
    },
    {
      id: uuidv4(),
      title: 'The Left Hand of Darkness',
      authors: ['Ursula K. Le Guin'],
      topics: ['Gender', 'Politics', 'Anthropology'],
      themes: ['Identity', 'Understanding', 'Love'],
      tags: ['sci-fi', 'feminist', 'award-winner'],
      year: 1969,
      rating: 5,
      dateRead: '2024-03-05',
    },
    {
      id: uuidv4(),
      title: 'Good Omens',
      authors: ['Neil Gaiman', 'Terry Pratchett'],
      topics: ['Religion', 'Apocalypse'],
      themes: ['Friendship', 'Free Will', 'Humor'],
      tags: ['fantasy', 'comedy', 'co-authored'],
      year: 1990,
      rating: 5,
      dateRead: '2024-04-12',
    },
    {
      id: uuidv4(),
      title: 'American Gods',
      authors: ['Neil Gaiman'],
      topics: ['Mythology', 'American Culture'],
      themes: ['Identity', 'Belief', 'Change'],
      tags: ['fantasy', 'mythology', 'award-winner'],
      year: 2001,
      rating: 4,
      dateRead: '2024-05-01',
    },
    {
      id: uuidv4(),
      title: 'The Name of the Wind',
      authors: ['Patrick Rothfuss'],
      topics: ['Magic', 'Education'],
      themes: ['Identity', 'Knowledge', 'Love'],
      tags: ['fantasy', 'epic', 'first-person'],
      year: 2007,
      rating: 5,
      dateRead: '2024-06-20',
    },
    {
      id: uuidv4(),
      title: 'Mistborn: The Final Empire',
      authors: ['Brandon Sanderson'],
      topics: ['Magic', 'Revolution'],
      themes: ['Power', 'Trust', 'Identity'],
      tags: ['fantasy', 'magic-system', 'series'],
      year: 2006,
      rating: 5,
      dateRead: '2024-07-15',
    },
    {
      id: uuidv4(),
      title: 'The Way of Kings',
      authors: ['Brandon Sanderson'],
      topics: ['War', 'Magic', 'Politics'],
      themes: ['Leadership', 'Honor', 'Identity'],
      tags: ['fantasy', 'epic', 'series'],
      year: 2010,
      rating: 5,
      dateRead: '2024-08-01',
      notes: 'First book in the Stormlight Archive.',
    },
  ];
}
